[package]
name = "pomoduro_clock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rodio = "0.17"
clap = { version = "4.2", features = ["derive"] }
